### PR TITLE
add a mysqldump timeout, configurable via env var and 600 sec by default

### PR DESCRIPTION
**Pull request by galkindmitrii**

### CODE REVIEW

**Comment by chuan137** [comment]
is it easy to add retry mysqldump on failure?

**Comment by galkindmitrii** [comment]
It is bash, everything is rather easy :)
The question is - we don't know why it was stuck few times over the last week for manila. I would rather retry only after some time. Backups as of now are hourly.

**Comment by chuan137** [comment]
Then I would suggest to skip uploading the tar ball in case of failure, to avoid corrupted data.

**Comment by galkindmitrii** [comment]
It will not upload, there is:
`|| exit 1`
timeout will sent SIGTERM when time runs out and the exit code will be 124, after _|| exit 1_ will force exit with status 1.

**Comment by galkindmitrii** [comment]
ok

**Pull request merged**
