### PR TITLE
Add influxdb backup

### PR DESCRIPTION
**Pull request by Dexus**
currently fixed port 8083

### CODE REVIEW

**Comment by jobrs** [comment]
very cool, thank you, Josef

Can you leave this PR open until we have caught up with our InfluxDB version?

**Comment by Dexus** [comment]
Sure Joachim, can you give a feedback when its done? So that can also create the PR for the configs and secrets?

**Comment by jobrs** [comment]
sure

**Comment by jobrs** [comment]
will do

**Comment by jobrs** [comment]
InfluxDB has been updated to 1.2

**Comment by jobrs** [comment]
@Dexus will this image now be built automatically?

**Comment by nobse** [comment]
It has to be triggered manually, after integrating the InfluxDB part into the backup script... will do this tomorrow.

**Comment by jobrs** [comment]
where do I find the values, e.g. backup_os_identity_api_version?

should I copy them from somewhere or will we have a shared values file to pass to helm (preferred)

**Pull request merged**
